name: Rebuild Grafana Agent Fedora

on:
#   schedule:
#     - cron: '0 0 * * *'  # run daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Install dependencies
      run: |
        curl -LO https://github.com/felicianotech/sonar/releases/download/v0.19.1/sonar-v0.19.1-amd64.deb
        sudo dpkg -i sonar-v0.19.1-amd64.deb

    - name: Check for new version
      id: check_version
      run: |
        LATEST_GRAFANA_HASH=$(curl -s https://registry.hub.docker.com/v2/repositories/grafana/agent/tags/latest | jq -r '.images[0].digest')
        BUILD_GRAFANA_HASH=$(sonar labels get signal24/grafana-agent-fedora grafana-agent-image-hash | cut -d' ' -f2)
        echo Latest Grafana hash: ${LATEST_GRAFANA_HASH}
        echo Build Grafana hash: ${BUILD_GRAFANA_HASH}
        
        if [ "$LATEST_GRAFANA_HASH" != "$BUILD_GRAFANA_HASH" ]; then
          echo "should_build=true" >> $GITHUB_OUTPUT
          echo "latest_grafana_hash=$LATEST_GRAFANA_HASH" >> $GITHUB_OUTPUT
        fi

    - name: Build and push
      if: steps.check_version.outputs.should_build == 'true'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: signal24/grafana-agent-fedora:latest
        build-args: |
          GRAFANA_SRC_HASH=${{ steps.check_version.outputs.latest_grafana_hash }}
